apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [ddp-job.yaml]
configMapGenerator:
  - name: allreduce-bench
    namespace: batch
    files: [allreduce_bench.py]
generatorOptions:
  disableNameSuffixHash: true
