apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources: [host-exporters.yaml, vcluster-workloads.yaml, rules.yaml]
configMapGenerator:
  - name: spark-k8s-dashboard
    files: [spark-k8s-dashboard.json]
    options:
      labels: {grafana_dashboard: "1"}      # kps Grafana sidecar picks it up
generatorOptions:
  disableNameSuffixHash: true
