apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [pd.yaml]
configMapGenerator:
  - name: pd-proxy
    namespace: llm-serving
    files: [pd_proxy.py]
generatorOptions:
  disableNameSuffixHash: true
