#!/usr/bin/env python3
"""Generate k8s/models/<name>/kustomization.yaml from models.yaml (Volume 19).

Each overlay patches the 02 Kubernetes vLLM Deployment: model, served name,
engine flags, memory. CI runs `gen_overlays.py --check` so the committed
overlays never drift from the catalog.
"""
import pathlib
import sys

import yaml

LAB = pathlib.Path(__file__).resolve().parent.parent
# Other modules (04 Qwen, …) reuse this generator for their own catalog:
#   python3 "../../03 DeepSeek/lab/scripts/gen_overlays.py" --lab .  [--check]
# Their lab must sit at the same depth (<module>/lab/k8s/models/<name>) so BASE resolves.


def _str(dumper, data):
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|" if "\n" in data else None)


yaml.add_representer(str, _str, Dumper=yaml.SafeDumper)
BASE = "../../../../../02 Kubernetes/lab/manifests/90-serving/vllm"


def overlay(m):
    args = ["$(MODEL)", "--served-model-name=$(SERVED_NAME)", "--host=0.0.0.0", "--port=8000",
            f"--gpu-memory-utilization={m['util']}", f"--max-model-len={m['max_len']}",
            "--enable-prefix-caching", "--download-dir=/models/hf", *m["args"]]
    if m.get("revision"):                      # pinned weights (Volume 33): the same commit for model + tokenizer
        args += [f"--revision={m['revision']}", f"--tokenizer-revision={m['revision']}"]
    patch = [
        {"op": "replace", "path": "/spec/template/spec/containers/0/args", "value": args},
        {"op": "replace", "path": "/spec/template/spec/containers/0/env/0/value", "value": m["hf"]},
        {"op": "replace", "path": "/spec/template/spec/containers/0/env/1/value", "value": m["name"]},
        {"op": "replace", "path": "/spec/template/spec/containers/0/resources/limits/memory", "value": m["mem"]},
        {"op": "replace", "path": "/metadata/labels/model", "value": m["name"]},
        {"op": "replace", "path": "/spec/template/metadata/labels/model", "value": m["name"]},
    ]
    doc = {"apiVersion": "kustomize.config.k8s.io/v1beta1", "kind": "Kustomization",
           "resources": [BASE],
           "patches": [{"target": {"kind": "Deployment", "name": "vllm"},
                        "patch": yaml.safe_dump(patch, sort_keys=False, width=200)}]}
    head = (f"# GENERATED by scripts/gen_overlays.py from models.yaml — do not edit.\n"
            f"# {m['name']}: {m['hf']}  (~{m['weights']} weights, util {m['util']})\n# {m['use']}\n")
    return head + yaml.safe_dump(doc, sort_keys=False, width=200)


def main():
    global LAB
    check = "--check" in sys.argv
    if "--lab" in sys.argv:
        LAB = pathlib.Path(sys.argv[sys.argv.index("--lab") + 1]).resolve()
    models = yaml.safe_load(open(LAB / "models.yaml"))["models"]
    drift = 0
    for m in models:
        path = LAB / "k8s" / "models" / m["name"] / "kustomization.yaml"
        text = overlay(m)
        if check:
            if not path.exists() or path.read_text() != text:
                print(f"DRIFT {path.relative_to(LAB)}")
                drift += 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    print(f"{len(models)} overlays {'checked' if check else 'written'}, {drift} drifted")
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
