apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [resilient-job.yaml]
configMapGenerator:
  - name: train-resilient
    namespace: batch
    files: [train_resilient.py]
generatorOptions:
  disableNameSuffixHash: true
